databases:
  - name: therapist-db
    databaseName: therapist_db
    user: therapist_db_user

services:
  - type: web
    name: therapist-api
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: therapist-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false